--- 
title: "Arrow Maintainer Dashboard"
author: "Alenka Frim and Nic Crane"
format: 
  dashboard:
    logo: ./images/arrow-logo.png
    nav-buttons: 
      - github
      - href: https://github.com/thisisnic/arrowdash/
---


```{r}
#| label: update
#| include: false
library(reticulate)
reticulate::use_virtualenv('r-arrow-dash')
library(DT)
update_time <- format(Sys.time(), "%a %b %d %X %Y %z")
```

Last updated: `{r} update_time`

```{python}
#| label: main methods
#| include: false
#| warning: false

import github_data.data as gd
data = gd.get_data()

import github_data.methods as gha

p_issues, p_prs = gha.get_all(data, "Python")
r_issues, r_prs = gha.get_all(data, "R")

p_issues_open = gha.get_open(p_issues)
r_issues_open = gha.get_open(r_issues)

p_prs_open = gha.get_open(p_prs)
r_prs_open = gha.get_open(r_prs)

p_issues_new_open = gha.get_new_contributors_open(p_issues)
r_issues_new_open = gha.get_new_contributors_open(r_issues)

p_prs_new_open = gha.get_new_contributors_open(p_prs)
r_prs_new_open = gha.get_new_contributors_open(r_prs)

p_issues_sum = gha.get_summary(p_issues)
p_prs_sum = gha.get_summary(p_prs)
r_issues_sum = gha.get_summary(r_issues)
r_prs_sum = gha.get_summary(r_prs)
```

# PyArrow

Issues, issues not yet closed (open issues) and pull requests created in the last 3 months. TODO: Questions?

## Row

```{python}
#| content: valuebox
#| title: "All issues"
dict(
  icon = "envelope",
  color = "light",
  value = len(p_issues)
)
```

```{python}
#| content: valuebox
#| title: "Open Issues"
dict(
  icon = "envelope-open",
  color = "light",
  value = len(p_issues_open)
)
```

```{python}
#| content: valuebox
#| title: "All Pull Requests"
dict(
  icon = "code-square",
  color = "light",
  value = len(p_prs_open)
)
```

```{python}
#| content: valuebox
#| title: "Stack Overflow Questions"
dict(
  icon = "question-circle",
  color = "light",
  value = "2"
)
```

## Row

### Column {width=50%}

```{python}
print(r_issues_open)
```

```{r}
test <- py$r_issues_open
head(test)
```

```{r}
#| eval: true
#| title: List of issues not yet closed
# datatable(
#   py$p_issues_open, extensions = 'Buttons', options = list(
#     dom = 'Bfrtip',
#     buttons = c('copy', 'csv', 'excel')
#   )
# )

# DT::datatable(r_issues_open)
# df <- data.frame(first_column = py$r_issues_open[, 1],
#                  second_column = py$r_issues_open[, 2]
#                  )
head(test[, 2])
```
